// Auto-generated by scripts/generate-translations.ts — do not edit manually
/* eslint-disable */
// NOTE: requires "resolveJsonModule": true in tsconfig

import attributes from '../../../apps/movie/src/i18n/uz/attributes.json';
import error from '../../../apps/movie/src/i18n/uz/error.json';
import success from '../../../apps/movie/src/i18n/uz/success.json';

export { attributes, error, success };

export const translations = {
  "attributes": attributes,
  "error": error,
  "success": success,
} as const;

export const flatTranslations = {
  "attributes.actor": attributes["actor"],
  "attributes.director": attributes["director"],
  "attributes.producer": attributes["producer"],
  "attributes.episode": attributes["episode"],
  "attributes.subscription": attributes["subscription"],
  "attributes.title": attributes["title"],
  "attributes.trailer": attributes["trailer"],
  "attributes.film_duration": attributes["film_duration"],
  "attributes.promo_code": attributes["promo_code"],
  "attributes.token": attributes["token"],
  "attributes.resource": attributes["resource"],
  "attributes.comment": attributes["comment"],
  "error.not_found": error["not_found"],
  "error.not_determined": error["not_determined"],
  "error.not_related": error["not_related"],
  "error.invalid": error["invalid"],
  "error.required": error["required"],
  "error.not_required": error["not_required"],
  "error.server_error": error["server_error"],
  "error.available": error["available"],
  "error.watching_duration_limited": error["watching_duration_limited"],
  "success.deleted": success["deleted"],
} as const;

export type TranslationKeys = keyof typeof flatTranslations;
